// ──────────────────────────────────────────────────────────────────────────────
// LetheCrypto.swift — F-052
//
// Every byte that crosses the wire is produced here. The relay never sees
// plaintext, and the room key never leaves this device — those two properties
// are the whole product, so this file is the one to be careful in.
//
// Wire format (identical to relay/scripts/chat-demo.mjs and the Dart client):
//
//     base64( nonce[12] ‖ ciphertext ‖ authTag[16] )
//
// That layout is exactly CryptoKit's `AES.GCM.SealedBox.combined`, so there is
// no hand-rolled framing here — which is the point. `LetheCryptoTests` pins it
// against vectors generated by the Node reference implementation.
//
// NOTHING in this file may log, print, or otherwise emit a key, a nonce, a
// plaintext or an invite link. Same discipline as PrivacyPatternDatabase.
// ──────────────────────────────────────────────────────────────────────────────

import Foundation
import CryptoKit

enum LetheCrypto {

    static let nonceLength = 12
    static let tagLength = 16
    static let keyLength = 32

    // MARK: - Key generation & room id

    /// A fresh 256-bit room key. Generated locally; never sent to the relay.
    static func generateRoomKey() -> Data {
        var bytes = [UInt8](repeating: 0, count: keyLength)
        // SecRandomCopyBytes can fail; a silently-weak key is far worse than a
        // crash, and CryptoKit's own generator is the correct fallback.
        if SecRandomCopyBytes(kSecRandomDefault, keyLength, &bytes) == errSecSuccess {
            return Data(bytes)
        }
        return SymmetricKey(size: .bits256).withUnsafeBytes { Data($0) }
    }

    /// `roomId = first 16 hex chars of SHA-256(roomKey)`.
    ///
    /// Must match `deriveRoomId` in `app/lib/crypto/key_derivation.dart` exactly
    /// — it is the only thing that makes two clients land in the same room.
    static func deriveRoomId(from roomKey: Data) -> String {
        let digest = SHA256.hash(data: roomKey)
        let hex = digest.map { String(format: "%02x", $0) }.joined()
        return String(hex.prefix(16))
    }

    // MARK: - Sealing

    /// Seal arbitrary bytes into `nonce ‖ ciphertext ‖ tag`.
    ///
    /// `nonce` is injectable for deterministic tests only. Production callers
    /// must omit it so CryptoKit generates a fresh random one per message —
    /// reusing a nonce under GCM is catastrophic, not merely weak.
    static func seal(_ plaintext: Data, key: Data, nonce: Data? = nil) throws -> Data {
        let symmetricKey = SymmetricKey(data: key)
        let box: AES.GCM.SealedBox
        if let nonce {
            box = try AES.GCM.seal(plaintext, using: symmetricKey, nonce: AES.GCM.Nonce(data: nonce))
        } else {
            box = try AES.GCM.seal(plaintext, using: symmetricKey)
        }
        // `.combined` is nonce ‖ ciphertext ‖ tag — the wire format verbatim.
        guard let combined = box.combined else {
            throw CryptoKitError.incorrectParameterSize
        }
        return combined
    }

    /// Open `nonce ‖ ciphertext ‖ tag`. Throws if the tag fails, which is the
    /// only signal we have that a blob came from a key-holder.
    static func open(_ combined: Data, key: Data) throws -> Data {
        guard combined.count >= nonceLength + tagLength else {
            throw LetheCryptoError.payloadTooShort
        }
        let box = try AES.GCM.SealedBox(combined: combined)
        return try AES.GCM.open(box, using: SymmetricKey(data: key))
    }

    // MARK: - Message payloads

    /// Encrypt a chat message into the base64 payload the relay forwards verbatim.
    ///
    /// The JSON must match what the Dart and Node clients emit *as bytes* — not
    /// merely be equivalent — so that the same plaintext under the same key and
    /// nonce produces the same ciphertext. See the encoder configuration below.
    static func encryptMessage(text: String,
                               handle: String,
                               roomKey: Data,
                               ts: Int64? = nil,
                               msgId: String? = nil,
                               nonce: Data? = nil) throws -> String {
        let payload = LethePayload(
            handle: handle,
            text: text,
            ts: ts ?? Int64(Date().timeIntervalSince1970 * 1000),
            msgId: msgId ?? newMsgId()
        )
        // Key ORDER is part of the contract, not cosmetic: the same plaintext
        // under the same key and nonce must produce the same ciphertext as the
        // Dart and Node clients, and JSON is order-sensitive as bytes.
        // Built by hand, and that is deliberate.
        //
        // `JSONEncoder` does NOT emit in property-declaration order — measured,
        // it produced `ts, text, msgId, handle` for this very struct — and
        // `JSONSerialization` on a Dictionary has no order at all
        // (`.sortedKeys` gives `handle, msgId, text, ts`, also wrong). Neither
        // can express "these four keys, in this order", which is what
        // byte-equality with the Dart and Node clients requires.
        let json = Data((
            "{"
            + "\"handle\":\"" + jsonEscape(payload.handle) + "\","
            + "\"text\":\"" + jsonEscape(payload.text) + "\","
            + "\"ts\":" + String(payload.ts) + ","
            + "\"msgId\":\"" + jsonEscape(payload.msgId) + "\""
            + "}"
        ).utf8)
        let sealed = try seal(json, key: roomKey, nonce: nonce)
        guard sealed.count <= LetheLimits.maxPayloadBytes else {
            throw LetheError.payloadTooLarge(bytes: sealed.count)
        }
        return sealed.base64EncodedString()
    }

    /// Escape a string exactly as `JSON.stringify` does.
    ///
    /// Notably it does **not** escape `/` (Foundation's encoder does) and does
    /// not escape non-ASCII (the emoji in the test vector must survive as raw
    /// UTF-8). Anything else below U+0020 becomes a `\\u00xx` escape.
    static func jsonEscape(_ s: String) -> String {
        var out = String()
        out.reserveCapacity(s.count + 8)
        for scalar in s.unicodeScalars {
            switch scalar {
            case "\"":      out += "\\\""
            case "\\":      out += "\\\\"
            case "\u{08}": out += "\\b"
            case "\u{09}": out += "\\t"
            case "\u{0A}": out += "\\n"
            case "\u{0C}": out += "\\f"
            case "\u{0D}": out += "\\r"
            default:
                if scalar.value < 0x20 {
                    out += String(format: "\\u%04x", scalar.value)
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        return out
    }

    /// Decrypt a base64 payload from the relay.
    static func decryptMessage(payload: String, roomKey: Data) throws -> LethePayload {
        guard let combined = Data(base64Encoded: payload) else {
            throw LetheCryptoError.notBase64
        }
        let clear = try open(combined, key: roomKey)
        return try JSONDecoder().decode(LethePayload.self, from: clear)
    }

    // MARK: - Short strings for invite links (base64url)

    /// Seal a short string to a URL-safe blob — used for the room name in an
    /// invite. Same `nonce ‖ ct ‖ tag` layout, base64url rather than base64.
    static func encryptStringURL(_ value: String, roomKey: Data, nonce: Data? = nil) throws -> String {
        let sealed = try seal(Data(value.utf8), key: roomKey, nonce: nonce)
        return base64URLEncode(sealed)
    }

    static func decryptStringURL(_ blob: String, roomKey: Data) throws -> String {
        guard let data = base64URLDecode(blob) else { throw LetheCryptoError.notBase64 }
        let clear = try open(data, key: roomKey)
        guard let s = String(data: clear, encoding: .utf8) else { throw LetheCryptoError.notUTF8 }
        return s
    }

    // MARK: - base64url

    /// Dart's `base64Url.encode` emits padding; Node's `base64url` does not.
    /// We emit padded (matching Dart, which is what produced the links users
    /// will paste) and accept either on the way in.
    static func base64URLEncode(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
    }

    static func base64URLDecode(_ s: String) -> Data? {
        var t = s.replacingOccurrences(of: "-", with: "+")
                 .replacingOccurrences(of: "_", with: "/")
        // Restore padding if the producer stripped it (Node does).
        let remainder = t.count % 4
        if remainder > 0 { t += String(repeating: "=", count: 4 - remainder) }
        return Data(base64Encoded: t)
    }

    // MARK: - Ids

    /// 128-bit random id as 32 lowercase hex chars — matches `newMsgId()` in
    /// the Dart client.
    static func newMsgId() -> String {
        var bytes = [UInt8](repeating: 0, count: 16)
        if SecRandomCopyBytes(kSecRandomDefault, 16, &bytes) != errSecSuccess {
            for i in bytes.indices { bytes[i] = UInt8.random(in: 0...255) }
        }
        return bytes.map { String(format: "%02x", $0) }.joined()
    }

    /// A throwaway handle in the shape the other clients use: `ghost_7f3a`.
    static func generateHandle() -> String {
        let words = ["ghost", "echo", "drift", "ember", "quiet", "shade",
                     "river", "cinder", "hollow", "vapor", "nomad", "willow"]
        var bytes = [UInt8](repeating: 0, count: 2)
        _ = SecRandomCopyBytes(kSecRandomDefault, 2, &bytes)
        let suffix = bytes.map { String(format: "%02x", $0) }.joined()
        return "\(words.randomElement() ?? "ghost")_\(suffix)"
    }
}

enum LetheCryptoError: LocalizedError, Equatable {
    case payloadTooShort
    case notBase64
    case notUTF8

    var errorDescription: String? {
        switch self {
        case .payloadTooShort: return "Encrypted payload is too short to be valid."
        case .notBase64:       return "Payload is not valid base64."
        case .notUTF8:         return "Decrypted bytes are not valid UTF-8."
        }
    }
}
