// ──────────────────────────────────────────────────────────────────────────────
// LetheModels.swift — F-052
//
// Value types for the Lethe module: anonymous ephemeral chat against the
// stateless relay at wss://lethe-relay.onrender.com.
//
// These mirror the wire contract implemented by the Flutter client and the Node
// relay (see docs/specs/F-052-lethe-ephemeral-chat.md). Anything here that
// crosses the wire is byte-compatible with those, and `LetheCryptoTests` pins it
// with vectors generated by the Node reference — a change on either side that
// breaks the other fails a test rather than a conversation.
// ──────────────────────────────────────────────────────────────────────────────

import Foundation

// MARK: - Room

/// A room as this device knows it.
///
/// The `key` is deliberately NOT stored here — it lives in the Keychain
/// (`RoomKeyStore`) and is fetched when needed, so a room can be listed,
/// persisted and rendered without the secret ever entering the JSON store.
struct LetheRoom: Identifiable, Codable, Equatable, Sendable {
    /// `roomId` — first 16 hex chars of SHA-256(roomKey). The only room
    /// identifier the relay ever sees, and it conveys nothing without the key.
    let id: String
    /// Local display name. Encrypted into the invite link; never sent to the relay.
    var name: String
    let createdAt: Date
    /// Unread since the room was last opened. Not persisted to the relay.
    var unreadCount: Int = 0

    init(id: String, name: String, createdAt: Date = Date(), unreadCount: Int = 0) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.unreadCount = unreadCount
    }
}

// MARK: - Message

/// A decrypted message. Only ever constructed after the AES-GCM tag verifies,
/// so an instance of this type is proof the sender held the room key.
struct LetheMessage: Identifiable, Codable, Equatable, Sendable {
    /// `msgId` from the payload — 32 hex chars. Used for dedup and, because the
    /// relay broadcasts to every socket in the room *including the sender*, for
    /// echo suppression.
    let id: String
    let roomId: String
    let handle: String
    let text: String
    /// Milliseconds since epoch, as written by the sending client.
    let ts: Int64
    /// True when this device sent it. Local only — not on the wire.
    var isOwn: Bool

    var date: Date { Date(timeIntervalSince1970: TimeInterval(ts) / 1000) }
}

/// The JSON that sits inside the encrypted payload. Field names are the wire
/// contract — do not rename.
struct LethePayload: Codable, Equatable, Sendable {
    let handle: String
    let text: String
    let ts: Int64
    let msgId: String
}

// MARK: - Connection

enum LetheConnectionState: Equatable, Sendable {
    case offline
    /// The relay runs on Render's free tier and spins down after ~15 min idle;
    /// the first connection after that can take ~50 s. That is a distinct state
    /// from "reconnecting" because it is expected rather than a fault, and
    /// showing an indefinite spinner for it reads as a hang.
    case waking
    case connecting
    case connected
    case reconnecting(attempt: Int)

    var isUsable: Bool { self == .connected }

    var label: String {
        switch self {
        case .offline:               return "Offline"
        case .waking:                return "Waking the relay…"
        case .connecting:            return "Connecting…"
        case .connected:             return "Connected"
        case .reconnecting(let n):   return "Reconnecting (attempt \(n))…"
        }
    }
}

// MARK: - Wire events

/// Frames the relay sends us. Parsing never throws — an unrecognised frame
/// becomes `.unknown` rather than killing the socket.
enum LetheServerEvent: Equatable, Sendable {
    case connected
    case message(roomId: String, payload: String, ts: Int64)
    case error(code: String, message: String)
    case unknown

    static func parse(_ raw: String) -> LetheServerEvent {
        guard let data = raw.data(using: .utf8),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let type = obj["type"] as? String
        else { return .unknown }

        switch type {
        case "CONNECTED":
            return .connected
        case "MESSAGE":
            guard let roomId = obj["roomId"] as? String,
                  let payload = obj["payload"] as? String
            else { return .unknown }
            // Relay sends ts as a JS number (ms). NSNumber covers Int and Double.
            let ts = (obj["ts"] as? NSNumber)?.int64Value ?? 0
            return .message(roomId: roomId, payload: payload, ts: ts)
        case "ERROR":
            return .error(code: obj["code"] as? String ?? "",
                          message: obj["message"] as? String ?? "")
        default:
            return .unknown
        }
    }
}

/// Frames we send. Encoded by hand rather than via `Codable` so the key order
/// and exact shape match the reference clients with no encoder surprises.
enum LetheClientFrame {
    case join(roomId: String)
    case send(roomId: String, payload: String)

    func encoded() -> String? {
        let obj: [String: Any]
        switch self {
        case .join(let roomId):
            obj = ["type": "JOIN", "roomId": roomId]
        case .send(let roomId, let payload):
            obj = ["type": "SEND", "roomId": roomId, "payload": payload]
        }
        guard let data = try? JSONSerialization.data(withJSONObject: obj) else { return nil }
        return String(data: data, encoding: .utf8)
    }
}

// MARK: - Errors

enum LetheError: LocalizedError, Equatable {
    case badInviteLink
    case keyNotFound(roomId: String)
    case payloadTooLarge(bytes: Int)
    case messageTooLong(count: Int)
    case notConnected

    var errorDescription: String? {
        switch self {
        case .badInviteLink:
            return "That doesn't look like a Lethe invite link."
        case .keyNotFound(let roomId):
            return "The key for room \(roomId) isn't on this Mac any more."
        case .payloadTooLarge(let bytes):
            return "Message is \(bytes) bytes encrypted; the relay's limit is \(LetheLimits.maxPayloadBytes)."
        case .messageTooLong(let count):
            return "Messages are limited to \(LetheLimits.maxMessageCharacters) characters (\(count) typed)."
        case .notConnected:
            return "Not connected to the relay."
        }
    }
}

// MARK: - Limits

/// Mirrors `relay/src/constants.js`. Enforced client-side so the user gets a
/// clear message instead of an opaque `ERROR` frame.
enum LetheLimits {
    static let maxPayloadBytes = 64 * 1024        // MAX_PAYLOAD_BYTES
    static let maxMessagesPerSecond = 10          // RATE_LIMIT_PER_SEC
    static let maxMessageCharacters = 2_000       // Lethe BRD F-18
    /// Local history cap per room (BRD NFR). The relay keeps only 50 for 6h.
    static let historyCapPerRoom = 1_000
    static let defaultRelayURL = "wss://lethe-relay.onrender.com"
}
